; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200

; WiFi连接方式配置
; 1 - 通过BLE蓝牙配网（默认）
; 2 - 直接连接WiFi，账号密码从下面读取
build_flags =
    -D WIFI_CONNECT_MODE=2
    -D WIFI_SSID=\"Ache\"
    -D WIFI_PASSWORD=\"1234qwer\"
    -D BASE_HOST=\"https://amigo.blestgirl.top\"
